import { useState } from 'react';
import {
  Box,
  Button,
  FormControl,
  MenuItem,
  Paper,
  Select,
  Stack,
  Tab,
  Tabs,
  Typography,
} from '@mui/material';
import {
  BoltRounded,
  ContentCopyRounded,
  FileDownloadRounded,
  RefreshRounded,
} from '@mui/icons-material';

import { useAASContext, MOCK_AAS_DB } from '@/context/AASContext';
import { useDialogContext } from '@/context/DialogContext';

// ═══════════════════════
// GENERATION STEPS
// ═══════════════════════

const GEN_STEPS = [
  'Parsing AAS metamodel…',
  'Generating Pydantic schemas…',
  'Creating route handlers…',
  'Building OpenAPI spec…',
  'Writing Dockerfile…',
  'Validating IDTA-01002-3-0…',
  '✓ Server generated',
];

// ═══════════════════════
// CODE GENERATORS
// ═══════════════════════

function generateMainPy(aasId: string, version: string, assetKind: string, submodels: { idShort: string; description?: string }[]): string {
  return `# Auto-generated AAS Server — ${aasId}
# IDTA-01002-3-0 compliant

from fastapi import FastAPI, HTTPException
from models import *

app = FastAPI(
    title="${aasId} AAS Server",
    version="${version}",
    description="Generated by AASStudio"
)

@app.get("/shells/{aas_id}")
async def get_shell(aas_id: str):
    return {"idShort": "${aasId}", "id": aas_id, "assetKind": "${assetKind}"}

@app.get("/shells/{aas_id}/submodels")
async def list_submodels(aas_id: str):
    return [${submodels.map(s => `"${s.idShort}"`).join(', ')}]
${submodels.map(s => `
@app.get("/submodels/${s.idShort}")
async def get_${s.idShort.toLowerCase()}():
    """${s.description || s.idShort}"""
    return ${s.idShort}Model()

@app.put("/submodels/${s.idShort}")
async def update_${s.idShort.toLowerCase()}(data: ${s.idShort}Model):
    return {"status": "updated", "submodel": "${s.idShort}"}
`).join('')}
@app.get("/health")
async def health():
    return {"status": "ok", "version": "${version}"}
`;
}

type ElementForServer = {
  type: string;
  idShort: string;
  valueType?: string;
  required: boolean;
};

function generateModelsPy(submodels: { idShort: string; elements: ElementForServer[] }[]): string {
  const typeMap: Record<string, string> = {
    'xs:int': 'int',
    'xs:double': 'float',
    'xs:float': 'float',
    'xs:boolean': 'bool',
    'xs:date': 'date',
    'xs:dateTime': 'datetime',
    'xs:anyURI': 'str',
    'xs:string': 'str',
  };
  return `from pydantic import BaseModel
from typing import Optional
from datetime import date, datetime
${submodels.map(s => `
class ${s.idShort}Model(BaseModel):
${(s.elements || []).filter(e => e.type === 'Property').map(e =>
    `    ${e.idShort}: ${typeMap[e.valueType || 'xs:string'] || 'str'}${e.required ? '' : ' = None'}`
  ).join('\n') || '    pass'}
`).join('')}`;
}

function generateDockerfile(): string {
  return `FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
`;
}

function generateRequirements(): string {
  return `fastapi>=0.110.0
uvicorn[standard]>=0.27.0
pydantic>=2.0.0
`;
}

// ═══════════════════════
// MAIN PAGE COMPONENT
// ═══════════════════════

type CodeTab = 'main' | 'models' | 'docker' | 'requirements';

export default function AASServer() {
  const { selectedModelId, setSelectedModelId, currentModel, currentVersion, submodels, aasIdShort } = useAASContext();
  const { setHandlers } = useDialogContext();

  const [generating, setGenerating] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [genProgress, setGenProgress] = useState<string[]>([]);
  const [activeTab, setActiveTab] = useState<CodeTab>('main');
  const [copied, setCopied] = useState(false);

  const runGeneration = () => {
    setGenerating(true);
    setGenerated(false);
    setGenProgress([]);
    GEN_STEPS.forEach((step, i) => {
      setTimeout(() => {
        setGenProgress(prev => [...prev, step]);
        if (i === GEN_STEPS.length - 1) {
          setGenerating(false);
          setGenerated(true);
        }
      }, (i + 1) * 500);
    });
  };

  const getCode = (): string => {
    if (!generated) return '';
    switch (activeTab) {
      case 'main': return generateMainPy(aasIdShort, currentVersion.version, currentModel.assetKind, submodels);
      case 'models': return generateModelsPy(submodels);
      case 'docker': return generateDockerfile();
      case 'requirements': return generateRequirements();
      default: return '';
    }
  };

  const handleCopy = async () => {
    const code = getCode();
    if (!code) return;
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const code = getCode();
    if (!code) return;
    const fileNames: Record<CodeTab, string> = { main: 'main.py', models: 'models.py', docker: 'Dockerfile', requirements: 'requirements.txt' };
    const blob = new Blob([code], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileNames[activeTab];
    a.click();
    URL.revokeObjectURL(url);
  };

  const tabs: { key: CodeTab; label: string }[] = [
    { key: 'main', label: 'main.py' },
    { key: 'models', label: 'models.py' },
    { key: 'docker', label: 'Dockerfile' },
    { key: 'requirements', label: 'requirements.txt' },
  ];

  // Register sidebar handlers
  useState(() => {
    setHandlers({ onGenerateServer: runGeneration, onDownloadServer: handleDownload });
    return () => setHandlers({});
  });

  return (
    <Box sx={{ flex: 1, display: 'flex', overflow: 'hidden' }}>

      {/* ── Left Panel ── */}
      <Box
        sx={{
          width: 300,
          borderRight: 1,
          borderColor: 'divider',
          bgcolor: 'background.paper',
          display: 'flex',
          flexDirection: 'column',
          p: 2.25,
          gap: 1.75,
          overflowY: 'auto',
          flexShrink: 0,
        }}
      >
        <Box>
          <Typography variant="subtitle1" fontWeight={700}>Server Generator</Typography>
          <Typography variant="caption" color="text.disabled" fontFamily="monospace" display="block">
            FastAPI · IDTA-01002-3-0
          </Typography>
        </Box>

        <Box>
          <Typography variant="overline" color="text.disabled" display="block" mb={0.75}>AAS Model</Typography>
          <FormControl size="small" fullWidth>
            <Select
              value={selectedModelId}
              onChange={(e) => setSelectedModelId(e.target.value)}
              sx={{ fontFamily: 'monospace', fontSize: 11 }}
            >
              {MOCK_AAS_DB.map(m => (
                <MenuItem key={m.id} value={m.id} sx={{ fontFamily: 'monospace', fontSize: 11 }}>
                  {m.idShort.replace('AAS_', '')}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
        </Box>

        <Paper variant="outlined" sx={{ p: 1.75 }}>
          <Typography variant="overline" color="text.disabled" display="block" mb={1.25}>source shell</Typography>
          <Typography variant="body2" fontWeight={600} mb={0.75}>{aasIdShort}</Typography>
          {([
            ['submodels', submodels.length],
            ['properties', submodels.flatMap(s => s.elements).filter(e => e.type === 'Property').length],
            ['operations', submodels.flatMap(s => s.elements).filter(e => e.type === 'Operation').length],
          ] as [string, number][]).map(([k, v]) => (
            <Stack key={k} direction="row" justifyContent="space-between" mb={0.5}>
              <Typography variant="caption" color="text.secondary" fontFamily="monospace">{k}</Typography>
              <Typography variant="caption" color="primary.main" fontFamily="monospace">{v}</Typography>
            </Stack>
          ))}
        </Paper>

        <Button
          variant="contained"
          onClick={runGeneration}
          disabled={generating}
          startIcon={generating || generated ? <RefreshRounded /> : <BoltRounded />}
          sx={{ fontWeight: 600 }}
        >
          {generating ? 'Generating…' : generated ? 'Regenerate' : 'Generate Server'}
        </Button>

        {(generating || generated) && genProgress.length > 0 && (
          <Paper variant="outlined" sx={{ p: 1.75 }}>
            <Stack spacing={0.75}>
              {genProgress.map((step, i) => (
                <Stack key={i} direction="row" alignItems="center" spacing={0.875}>
                  <Box
                    sx={{
                      width: 5, height: 5, borderRadius: '50%', flexShrink: 0,
                      bgcolor: i === genProgress.length - 1 && generated ? 'success.main' : 'text.disabled',
                    }}
                  />
                  <Typography
                    variant="caption"
                    fontFamily="monospace"
                    color={i === genProgress.length - 1 && generated ? 'success.main' : 'text.secondary'}
                  >
                    {step}
                  </Typography>
                </Stack>
              ))}
            </Stack>
          </Paper>
        )}

        {generated && (
          <Paper variant="outlined" sx={{ p: 1.75, borderColor: 'success.main', bgcolor: 'rgba(16,185,129,.05)' }}>
            <Typography variant="caption" fontWeight={600} color="success.main" display="block" mb={0.75}>
              Server config
            </Typography>
            <Typography variant="caption" fontFamily="monospace" color="text.secondary" sx={{ lineHeight: 1.9 }} component="div">
              Host: 0.0.0.0:8000<br />
              Runtime: Python 3.12<br />
              Framework: FastAPI 0.110<br />
              Spec: IDTA-01002-3-0
            </Typography>
          </Paper>
        )}
      </Box>

      {/* ── Right: Code Panel ── */}
      <Box sx={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
        <Stack
          direction="row"
          alignItems="center"
          sx={{ px: 2, borderBottom: 1, borderColor: 'divider', bgcolor: 'background.paper', flexShrink: 0 }}
        >
          <Tabs
            value={activeTab}
            onChange={(_, v) => setActiveTab(v as CodeTab)}
            textColor="inherit"
            TabIndicatorProps={{ style: { height: 2 } }}
          >
            {tabs.map(tab => (
              <Tab
                key={tab.key}
                value={tab.key}
                label={tab.label}
                sx={{ fontFamily: 'monospace', fontSize: 11, minHeight: 44, textTransform: 'none' }}
              />
            ))}
          </Tabs>
          <Box flexGrow={1} />
          {generated && (
            <Stack direction="row" spacing={0.75}>
              <Button
                size="small"
                variant="text"
                startIcon={<ContentCopyRounded sx={{ fontSize: 13 }} />}
                onClick={handleCopy}
                color={copied ? 'success' : 'inherit'}
              >
                {copied ? 'Copied!' : 'Copy'}
              </Button>
              <Button
                size="small"
                variant="outlined"
                startIcon={<FileDownloadRounded sx={{ fontSize: 13 }} />}
                onClick={handleDownload}
              >
                Download
              </Button>
            </Stack>
          )}
        </Stack>

        <Box sx={{ flex: 1, overflow: 'auto', p: 2.5 }}>
          {!generated ? (
            <Stack alignItems="center" justifyContent="center" height="100%" spacing={1}>
              <Typography fontSize={30}>⚡</Typography>
              <Typography variant="body2" color="text.secondary" fontWeight={500}>
                Clicca "Generate Server" per iniziare
              </Typography>
              <Typography variant="caption" fontFamily="monospace" color="text.disabled">
                {submodels.length} submodel{submodels.length !== 1 ? 's' : ''} · FastAPI · IDTA compliant
              </Typography>
            </Stack>
          ) : (
            <pre style={{ fontSize: 11, fontFamily: "'JetBrains Mono', 'Fira Code', monospace", lineHeight: 1.7, whiteSpace: 'pre-wrap', margin: 0 }}>
              {getCode()}
            </pre>
          )}
        </Box>
      </Box>
    </Box>
  );
}
